export const ELO_TEAM_MAP: Record<string, string> = {
  "Manchester City": "ManCity",
  "Manchester United": "ManUnited",
  "Real Madrid": "Real",
  "PSG": "ParisSG",
  "Paris Saint-Germain": "ParisSG",
  "Bayern Munich": "Bayern",
  "Arsenal": "Arsenal",
  "Liverpool": "Liverpool",
  "Chelsea": "Chelsea",
  "Tottenham Hotspur": "Tottenham",
  "Barcelona": "Barcelona",
  "Atletico Madrid": "Atletico",
  "Juventus": "Juventus",
  "AC Milan": "Milan",
  "Inter Milan": "Inter",
  "Napoli": "Napoli",
  "Borussia Dortmund": "Dortmund",
  "RB Leipzig": "Leipzig",
  "Bayer Leverkusen": "Leverkusen",
  "Ajax": "Ajax",
  "PSV Eindhoven": "PSV",
  "Benfica": "Benfica",
  "FC Porto": "Porto",
  "Sporting CP": "Sporting",
  "Newcastle United": "Newcastle",
  "Aston Villa": "AstonVilla",
  "Brighton & Hove Albion": "Brighton",
  "West Ham United": "WestHam",
  "Everton": "Everton",
  "Leicester City": "Leicester",
  "Lazio": "Lazio",
  "Roma": "Roma",
  "Atalanta": "Atalanta",
  "Fiorentina": "Fiorentina",
  "Sevilla": "Sevilla",
  "Real Sociedad": "RealSociedad",
  "Villarreal": "Villarreal",
  "Real Betis": "Betis",
  "Monaco": "Monaco",
  "Marseille": "Marseille",
  "Lyon": "Lyon",
  "Lille": "Lille",
  "Lens": "Lens",
  "Rennes": "Rennes",
};

export function mapToEloName(teamName: string): string {
  return ELO_TEAM_MAP[teamName] || teamName.replace(/\s+/g, '');
}
